// Copyright 2026, Command Line Inc.
// SPDX-License-Identifier: Apache-2.0

// generated by cmd/generate/main-generatets.go

import { WshClient } from "./wshclient";

export interface MockRpcClient {
    mockWshRpcCall(client: WshClient, command: string, data: any, opts?: RpcOpts): Promise<any>;
    mockWshRpcStream(client: WshClient, command: string, data: any, opts?: RpcOpts): AsyncGenerator<any, void, boolean>;
}

// WshServerCommandToDeclMap
export class RpcApiType {
    mockClient: MockRpcClient = null;

    setMockRpcClient(client: MockRpcClient): void {
        this.mockClient = client;
    }

    // command "activatewindow" [call]
    ActivateWindowCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "activatewindow", data, opts);
        return client.wshRpcCall("activatewindow", data, opts);
    }

    // command "activity" [call]
    ActivityCommand(client: WshClient, data: ActivityUpdate, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "activity", data, opts);
        return client.wshRpcCall("activity", data, opts);
    }

    // command "aisendmessage" [call]
    AiSendMessageCommand(client: WshClient, data: AiMessageData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "aisendmessage", data, opts);
        return client.wshRpcCall("aisendmessage", data, opts);
    }

    // command "appstreamaction" [call]
    AppStreamActionCommand(client: WshClient, data: AppStreamActionRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "appstreamaction", data, opts);
        return client.wshRpcCall("appstreamaction", data, opts);
    }

    // command "appstreamstart" [call]
    AppStreamStartCommand(client: WshClient, data: AppStreamStartRequest, opts?: RpcOpts): Promise<AppStreamStartResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "appstreamstart", data, opts);
        return client.wshRpcCall("appstreamstart", data, opts);
    }

    // command "appstreamstop" [call]
    AppStreamStopCommand(client: WshClient, data: AppStreamStopRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "appstreamstop", data, opts);
        return client.wshRpcCall("appstreamstop", data, opts);
    }

    // command "authenticate" [call]
    AuthenticateCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticate", data, opts);
        return client.wshRpcCall("authenticate", data, opts);
    }

    // command "authenticatejobmanager" [call]
    AuthenticateJobManagerCommand(client: WshClient, data: CommandAuthenticateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatejobmanager", data, opts);
        return client.wshRpcCall("authenticatejobmanager", data, opts);
    }

    // command "authenticatejobmanagerverify" [call]
    AuthenticateJobManagerVerifyCommand(client: WshClient, data: CommandAuthenticateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatejobmanagerverify", data, opts);
        return client.wshRpcCall("authenticatejobmanagerverify", data, opts);
    }

    // command "authenticatetojobmanager" [call]
    AuthenticateToJobManagerCommand(client: WshClient, data: CommandAuthenticateToJobData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatetojobmanager", data, opts);
        return client.wshRpcCall("authenticatetojobmanager", data, opts);
    }

    // command "authenticatetoken" [call]
    AuthenticateTokenCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatetoken", data, opts);
        return client.wshRpcCall("authenticatetoken", data, opts);
    }

    // command "authenticatetokenverify" [call]
    AuthenticateTokenVerifyCommand(client: WshClient, data: CommandAuthenticateTokenData, opts?: RpcOpts): Promise<CommandAuthenticateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "authenticatetokenverify", data, opts);
        return client.wshRpcCall("authenticatetokenverify", data, opts);
    }

    // command "badgewatchpid" [call]
    BadgeWatchPidCommand(client: WshClient, data: CommandBadgeWatchPidData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "badgewatchpid", data, opts);
        return client.wshRpcCall("badgewatchpid", data, opts);
    }

    // command "blockinfo" [call]
    BlockInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<BlockInfoData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "blockinfo", data, opts);
        return client.wshRpcCall("blockinfo", data, opts);
    }

    // command "blockjobstatus" [call]
    BlockJobStatusCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<BlockJobStatusData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "blockjobstatus", data, opts);
        return client.wshRpcCall("blockjobstatus", data, opts);
    }

    // command "blockslist" [call]
    BlocksListCommand(client: WshClient, data: BlocksListRequest, opts?: RpcOpts): Promise<BlocksListEntry[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "blockslist", data, opts);
        return client.wshRpcCall("blockslist", data, opts);
    }

    // command "bookmarkcreate" [call]
    BookmarkCreateCommand(client: WshClient, data: BookmarkCreateData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarkcreate", data, opts);
        return client.wshRpcCall("bookmarkcreate", data, opts);
    }

    // command "bookmarklist" [call]
    BookmarkListCommand(client: WshClient, opts?: RpcOpts): Promise<{[key: string]: WebBookmark}> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarklist", null, opts);
        return client.wshRpcCall("bookmarklist", null, opts);
    }

    // command "bookmarkmove" [call]
    BookmarkMoveCommand(client: WshClient, data: BookmarkMoveData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarkmove", data, opts);
        return client.wshRpcCall("bookmarkmove", data, opts);
    }

    // command "bookmarkremove" [call]
    BookmarkRemoveCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarkremove", data, opts);
        return client.wshRpcCall("bookmarkremove", data, opts);
    }

    // command "bookmarksearch" [call]
    BookmarkSearchCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<BookmarkSearchResult[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarksearch", data, opts);
        return client.wshRpcCall("bookmarksearch", data, opts);
    }

    // command "bookmarkupdate" [call]
    BookmarkUpdateCommand(client: WshClient, data: BookmarkUpdateData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "bookmarkupdate", data, opts);
        return client.wshRpcCall("bookmarkupdate", data, opts);
    }

    // command "browserosinfo" [call]
    BrowserOSInfoCommand(client: WshClient, opts?: RpcOpts): Promise<BrowserOSInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "browserosinfo", null, opts);
        return client.wshRpcCall("browserosinfo", null, opts);
    }

    // command "canvasassetupload" [call]
    CanvasAssetUploadCommand(client: WshClient, data: CanvasAssetUploadRequest, opts?: RpcOpts): Promise<CanvasAssetUploadResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasassetupload", data, opts);
        return client.wshRpcCall("canvasassetupload", data, opts);
    }

    // command "canvasconnectnodes" [call]
    CanvasConnectNodesCommand(client: WshClient, data: CanvasConnectNodesRequest, opts?: RpcOpts): Promise<CanvasEdge> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasconnectnodes", data, opts);
        return client.wshRpcCall("canvasconnectnodes", data, opts);
    }

    // command "canvascreatenode" [call]
    CanvasCreateNodeCommand(client: WshClient, data: CanvasNodeMutationRequest, opts?: RpcOpts): Promise<CanvasNode> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvascreatenode", data, opts);
        return client.wshRpcCall("canvascreatenode", data, opts);
    }

    // command "canvasdeletenode" [call]
    CanvasDeleteNodeCommand(client: WshClient, data: CanvasNodeIdRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasdeletenode", data, opts);
        return client.wshRpcCall("canvasdeletenode", data, opts);
    }

    // command "canvaslaunchnode" [call]
    CanvasLaunchNodeCommand(client: WshClient, data: CanvasLaunchNodeRequest, opts?: RpcOpts): Promise<CanvasLaunchNodeResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvaslaunchnode", data, opts);
        return client.wshRpcCall("canvaslaunchnode", data, opts);
    }

    // command "canvasload" [call]
    CanvasLoadCommand(client: WshClient, data: CanvasLoadRequest, opts?: RpcOpts): Promise<CanvasLoadResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasload", data, opts);
        return client.wshRpcCall("canvasload", data, opts);
    }

    // command "canvassave" [call]
    CanvasSaveCommand(client: WshClient, data: CanvasSaveRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvassave", data, opts);
        return client.wshRpcCall("canvassave", data, opts);
    }

    // command "canvassnapshot" [call]
    CanvasSnapshotCommand(client: WshClient, data: CanvasSnapshotRequest, opts?: RpcOpts): Promise<CanvasSnapshotResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvassnapshot", data, opts);
        return client.wshRpcCall("canvassnapshot", data, opts);
    }

    // command "canvasupdatenode" [call]
    CanvasUpdateNodeCommand(client: WshClient, data: CanvasNodeMutationRequest, opts?: RpcOpts): Promise<CanvasNode> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "canvasupdatenode", data, opts);
        return client.wshRpcCall("canvasupdatenode", data, opts);
    }

    // command "captureblockscreenshot" [call]
    CaptureBlockScreenshotCommand(client: WshClient, data: CommandCaptureBlockScreenshotData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "captureblockscreenshot", data, opts);
        return client.wshRpcCall("captureblockscreenshot", data, opts);
    }

    // command "closetabgroup" [call]
    CloseTabGroupCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "closetabgroup", data, opts);
        return client.wshRpcCall("closetabgroup", data, opts);
    }

    // command "closewindow" [call]
    CloseWindowCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "closewindow", data, opts);
        return client.wshRpcCall("closewindow", data, opts);
    }

    // command "connconnect" [call]
    ConnConnectCommand(client: WshClient, data: ConnRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connconnect", data, opts);
        return client.wshRpcCall("connconnect", data, opts);
    }

    // command "conndisconnect" [call]
    ConnDisconnectCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "conndisconnect", data, opts);
        return client.wshRpcCall("conndisconnect", data, opts);
    }

    // command "connensure" [call]
    ConnEnsureCommand(client: WshClient, data: ConnExtData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connensure", data, opts);
        return client.wshRpcCall("connensure", data, opts);
    }

    // command "connlist" [call]
    ConnListCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connlist", null, opts);
        return client.wshRpcCall("connlist", null, opts);
    }

    // command "connreinstallwsh" [call]
    ConnReinstallWshCommand(client: WshClient, data: ConnExtData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connreinstallwsh", data, opts);
        return client.wshRpcCall("connreinstallwsh", data, opts);
    }

    // command "connserverinit" [call]
    ConnServerInitCommand(client: WshClient, data: CommandConnServerInitData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connserverinit", data, opts);
        return client.wshRpcCall("connserverinit", data, opts);
    }

    // command "connstatus" [call]
    ConnStatusCommand(client: WshClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connstatus", null, opts);
        return client.wshRpcCall("connstatus", null, opts);
    }

    // command "connupdatewsh" [call]
    ConnUpdateWshCommand(client: WshClient, data: RemoteInfo, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "connupdatewsh", data, opts);
        return client.wshRpcCall("connupdatewsh", data, opts);
    }

    // command "controlgetrouteid" [call]
    ControlGetRouteIdCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controlgetrouteid", null, opts);
        return client.wshRpcCall("controlgetrouteid", null, opts);
    }

    // command "controllerappendoutput" [call]
    ControllerAppendOutputCommand(client: WshClient, data: CommandControllerAppendOutputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerappendoutput", data, opts);
        return client.wshRpcCall("controllerappendoutput", data, opts);
    }

    // command "controllerdestroy" [call]
    ControllerDestroyCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerdestroy", data, opts);
        return client.wshRpcCall("controllerdestroy", data, opts);
    }

    // command "controllerinput" [call]
    ControllerInputCommand(client: WshClient, data: CommandBlockInputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerinput", data, opts);
        return client.wshRpcCall("controllerinput", data, opts);
    }

    // command "controllerresync" [call]
    ControllerResyncCommand(client: WshClient, data: CommandControllerResyncData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "controllerresync", data, opts);
        return client.wshRpcCall("controllerresync", data, opts);
    }

    // command "createblock" [call]
    CreateBlockCommand(client: WshClient, data: CommandCreateBlockData, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createblock", data, opts);
        return client.wshRpcCall("createblock", data, opts);
    }

    // command "createsubblock" [call]
    CreateSubBlockCommand(client: WshClient, data: CommandCreateSubBlockData, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createsubblock", data, opts);
        return client.wshRpcCall("createsubblock", data, opts);
    }

    // command "createsurfacetoken" [call]
    CreateSurfaceTokenCommand(client: WshClient, data: CommandCreateSurfaceTokenData, opts?: RpcOpts): Promise<CommandCreateSurfaceTokenRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createsurfacetoken", data, opts);
        return client.wshRpcCall("createsurfacetoken", data, opts);
    }

    // command "createwindow" [call]
    CreateWindowCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "createwindow", null, opts);
        return client.wshRpcCall("createwindow", null, opts);
    }

    // command "debugterm" [call]
    DebugTermCommand(client: WshClient, data: CommandDebugTermData, opts?: RpcOpts): Promise<CommandDebugTermRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "debugterm", data, opts);
        return client.wshRpcCall("debugterm", data, opts);
    }

    // command "deleteblock" [call]
    DeleteBlockCommand(client: WshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "deleteblock", data, opts);
        return client.wshRpcCall("deleteblock", data, opts);
    }

    // command "deletesubblock" [call]
    DeleteSubBlockCommand(client: WshClient, data: CommandDeleteBlockData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "deletesubblock", data, opts);
        return client.wshRpcCall("deletesubblock", data, opts);
    }

    // command "dismisswshfail" [call]
    DismissWshFailCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dismisswshfail", data, opts);
        return client.wshRpcCall("dismisswshfail", data, opts);
    }

    // command "dispose" [call]
    DisposeCommand(client: WshClient, data: CommandDisposeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "dispose", data, opts);
        return client.wshRpcCall("dispose", data, opts);
    }

    // command "disposesuggestions" [call]
    DisposeSuggestionsCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "disposesuggestions", data, opts);
        return client.wshRpcCall("disposesuggestions", data, opts);
    }

    // command "electrondecrypt" [call]
    ElectronDecryptCommand(client: WshClient, data: CommandElectronDecryptData, opts?: RpcOpts): Promise<CommandElectronDecryptRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "electrondecrypt", data, opts);
        return client.wshRpcCall("electrondecrypt", data, opts);
    }

    // command "electronencrypt" [call]
    ElectronEncryptCommand(client: WshClient, data: CommandElectronEncryptData, opts?: RpcOpts): Promise<CommandElectronEncryptRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "electronencrypt", data, opts);
        return client.wshRpcCall("electronencrypt", data, opts);
    }

    // command "electronsystembell" [call]
    ElectronSystemBellCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "electronsystembell", null, opts);
        return client.wshRpcCall("electronsystembell", null, opts);
    }

    // command "eventpublish" [call]
    EventPublishCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventpublish", data, opts);
        return client.wshRpcCall("eventpublish", data, opts);
    }

    // command "eventreadhistory" [call]
    EventReadHistoryCommand(client: WshClient, data: CommandEventReadHistoryData, opts?: RpcOpts): Promise<WaveEvent[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventreadhistory", data, opts);
        return client.wshRpcCall("eventreadhistory", data, opts);
    }

    // command "eventrecv" [call]
    EventRecvCommand(client: WshClient, data: WaveEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventrecv", data, opts);
        return client.wshRpcCall("eventrecv", data, opts);
    }

    // command "eventsub" [call]
    EventSubCommand(client: WshClient, data: SubscriptionRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventsub", data, opts);
        return client.wshRpcCall("eventsub", data, opts);
    }

    // command "eventunsub" [call]
    EventUnsubCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventunsub", data, opts);
        return client.wshRpcCall("eventunsub", data, opts);
    }

    // command "eventunsuball" [call]
    EventUnsubAllCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "eventunsuball", null, opts);
        return client.wshRpcCall("eventunsuball", null, opts);
    }

    // command "fetchsuggestions" [call]
    FetchSuggestionsCommand(client: WshClient, data: FetchSuggestionsData, opts?: RpcOpts): Promise<FetchSuggestionsResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fetchsuggestions", data, opts);
        return client.wshRpcCall("fetchsuggestions", data, opts);
    }

    // command "fileappend" [call]
    FileAppendCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fileappend", data, opts);
        return client.wshRpcCall("fileappend", data, opts);
    }

    // command "filecopy" [call]
    FileCopyCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filecopy", data, opts);
        return client.wshRpcCall("filecopy", data, opts);
    }

    // command "filecreate" [call]
    FileCreateCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filecreate", data, opts);
        return client.wshRpcCall("filecreate", data, opts);
    }

    // command "filedelete" [call]
    FileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filedelete", data, opts);
        return client.wshRpcCall("filedelete", data, opts);
    }

    // command "fileinfo" [call]
    FileInfoCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fileinfo", data, opts);
        return client.wshRpcCall("fileinfo", data, opts);
    }

    // command "filejoin" [call]
    FileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filejoin", data, opts);
        return client.wshRpcCall("filejoin", data, opts);
    }

    // command "filelist" [call]
    FileListCommand(client: WshClient, data: FileListData, opts?: RpcOpts): Promise<FileInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filelist", data, opts);
        return client.wshRpcCall("filelist", data, opts);
    }

    // command "fileliststream" [responsestream]
	FileListStreamCommand(client: WshClient, data: FileListData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "fileliststream", data, opts);
        return client.wshRpcStream("fileliststream", data, opts);
    }

    // command "filemkdir" [call]
    FileMkdirCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filemkdir", data, opts);
        return client.wshRpcCall("filemkdir", data, opts);
    }

    // command "filemove" [call]
    FileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filemove", data, opts);
        return client.wshRpcCall("filemove", data, opts);
    }

    // command "fileread" [call]
    FileReadCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<FileData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "fileread", data, opts);
        return client.wshRpcCall("fileread", data, opts);
    }

    // command "filereadstream" [responsestream]
	FileReadStreamCommand(client: WshClient, data: FileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "filereadstream", data, opts);
        return client.wshRpcStream("filereadstream", data, opts);
    }

    // command "filerestorebackup" [call]
    FileRestoreBackupCommand(client: WshClient, data: CommandFileRestoreBackupData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filerestorebackup", data, opts);
        return client.wshRpcCall("filerestorebackup", data, opts);
    }

    // command "filestream" [call]
    FileStreamCommand(client: WshClient, data: CommandFileStreamData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filestream", data, opts);
        return client.wshRpcCall("filestream", data, opts);
    }

    // command "filewrite" [call]
    FileWriteCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "filewrite", data, opts);
        return client.wshRpcCall("filewrite", data, opts);
    }

    // command "findgitbash" [call]
    FindGitBashCommand(client: WshClient, data: boolean, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "findgitbash", data, opts);
        return client.wshRpcCall("findgitbash", data, opts);
    }

    // command "focuswindow" [call]
    FocusWindowCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "focuswindow", data, opts);
        return client.wshRpcCall("focuswindow", data, opts);
    }

    // command "getallbadges" [call]
    GetAllBadgesCommand(client: WshClient, opts?: RpcOpts): Promise<BadgeEvent[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getallbadges", null, opts);
        return client.wshRpcCall("getallbadges", null, opts);
    }

    // command "getallvars" [call]
    GetAllVarsCommand(client: WshClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getallvars", data, opts);
        return client.wshRpcCall("getallvars", data, opts);
    }

    // command "getblockcontent" [call]
    GetBlockContentCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<CommandGetBlockContentRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getblockcontent", data, opts);
        return client.wshRpcCall("getblockcontent", data, opts);
    }

    // command "getfocusedblockdata" [call]
    GetFocusedBlockDataCommand(client: WshClient, opts?: RpcOpts): Promise<FocusedBlockData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getfocusedblockdata", null, opts);
        return client.wshRpcCall("getfocusedblockdata", null, opts);
    }

    // command "getfullconfig" [call]
    GetFullConfigCommand(client: WshClient, opts?: RpcOpts): Promise<FullConfigType> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getfullconfig", null, opts);
        return client.wshRpcCall("getfullconfig", null, opts);
    }

    // command "getjwtpublickey" [call]
    GetJwtPublicKeyCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getjwtpublickey", null, opts);
        return client.wshRpcCall("getjwtpublickey", null, opts);
    }

    // command "getmeta" [call]
    GetMetaCommand(client: WshClient, data: CommandGetMetaData, opts?: RpcOpts): Promise<MetaType> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getmeta", data, opts);
        return client.wshRpcCall("getmeta", data, opts);
    }

    // command "getrtinfo" [call]
    GetRTInfoCommand(client: WshClient, data: CommandGetRTInfoData, opts?: RpcOpts): Promise<ObjRTInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getrtinfo", data, opts);
        return client.wshRpcCall("getrtinfo", data, opts);
    }

    // command "getsecrets" [call]
    GetSecretsCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<{[key: string]: string}> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsecrets", data, opts);
        return client.wshRpcCall("getsecrets", data, opts);
    }

    // command "getsecretslinuxstoragebackend" [call]
    GetSecretsLinuxStorageBackendCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsecretslinuxstoragebackend", null, opts);
        return client.wshRpcCall("getsecretslinuxstoragebackend", null, opts);
    }

    // command "getsecretsnames" [call]
    GetSecretsNamesCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getsecretsnames", null, opts);
        return client.wshRpcCall("getsecretsnames", null, opts);
    }

    // command "gettab" [call]
    GetTabCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<Tab> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gettab", data, opts);
        return client.wshRpcCall("gettab", data, opts);
    }

    // command "gettempdir" [call]
    GetTempDirCommand(client: WshClient, data: CommandGetTempDirData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "gettempdir", data, opts);
        return client.wshRpcCall("gettempdir", data, opts);
    }

    // command "getupdatechannel" [call]
    GetUpdateChannelCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getupdatechannel", null, opts);
        return client.wshRpcCall("getupdatechannel", null, opts);
    }

    // command "getvar" [call]
    GetVarCommand(client: WshClient, data: CommandVarData, opts?: RpcOpts): Promise<CommandVarResponseData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getvar", data, opts);
        return client.wshRpcCall("getvar", data, opts);
    }

    // command "getwaveaichat" [call]
    GetWaveAIChatCommand(client: WshClient, data: CommandGetWaveAIChatData, opts?: RpcOpts): Promise<UIChat> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getwaveaichat", data, opts);
        return client.wshRpcCall("getwaveaichat", data, opts);
    }

    // command "getwaveaimodeconfig" [call]
    GetWaveAIModeConfigCommand(client: WshClient, opts?: RpcOpts): Promise<AIModeConfigUpdate> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getwaveaimodeconfig", null, opts);
        return client.wshRpcCall("getwaveaimodeconfig", null, opts);
    }

    // command "getwaveairatelimit" [call]
    GetWaveAIRateLimitCommand(client: WshClient, opts?: RpcOpts): Promise<RateLimitInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "getwaveairatelimit", null, opts);
        return client.wshRpcCall("getwaveairatelimit", null, opts);
    }

    // command "grouptabs" [call]
    GroupTabsCommand(client: WshClient, data: GroupTabsData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "grouptabs", data, opts);
        return client.wshRpcCall("grouptabs", data, opts);
    }

    // command "historydeleterange" [call]
    HistoryDeleteRangeCommand(client: WshClient, data: HistoryDeleteRangeData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "historydeleterange", data, opts);
        return client.wshRpcCall("historydeleterange", data, opts);
    }

    // command "historydeleteurl" [call]
    HistoryDeleteUrlCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "historydeleteurl", data, opts);
        return client.wshRpcCall("historydeleteurl", data, opts);
    }

    // command "historyrecent" [call]
    HistoryRecentCommand(client: WshClient, data: number, opts?: RpcOpts): Promise<HistoryEntry[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "historyrecent", data, opts);
        return client.wshRpcCall("historyrecent", data, opts);
    }

    // command "historysearch" [call]
    HistorySearchCommand(client: WshClient, data: HistorySearchData, opts?: RpcOpts): Promise<HistoryEntry[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "historysearch", data, opts);
        return client.wshRpcCall("historysearch", data, opts);
    }

    // command "jobcmdexited" [call]
    JobCmdExitedCommand(client: WshClient, data: CommandJobCmdExitedData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcmdexited", data, opts);
        return client.wshRpcCall("jobcmdexited", data, opts);
    }

    // command "jobcontrollerattachjob" [call]
    JobControllerAttachJobCommand(client: WshClient, data: CommandJobControllerAttachJobData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerattachjob", data, opts);
        return client.wshRpcCall("jobcontrollerattachjob", data, opts);
    }

    // command "jobcontrollerconnectedjobs" [call]
    JobControllerConnectedJobsCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerconnectedjobs", null, opts);
        return client.wshRpcCall("jobcontrollerconnectedjobs", null, opts);
    }

    // command "jobcontrollerdeletejob" [call]
    JobControllerDeleteJobCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerdeletejob", data, opts);
        return client.wshRpcCall("jobcontrollerdeletejob", data, opts);
    }

    // command "jobcontrollerdetachjob" [call]
    JobControllerDetachJobCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerdetachjob", data, opts);
        return client.wshRpcCall("jobcontrollerdetachjob", data, opts);
    }

    // command "jobcontrollerdisconnectjob" [call]
    JobControllerDisconnectJobCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerdisconnectjob", data, opts);
        return client.wshRpcCall("jobcontrollerdisconnectjob", data, opts);
    }

    // command "jobcontrollerexitjob" [call]
    JobControllerExitJobCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerexitjob", data, opts);
        return client.wshRpcCall("jobcontrollerexitjob", data, opts);
    }

    // command "jobcontrollergetalljobmanagerstatus" [call]
    JobControllerGetAllJobManagerStatusCommand(client: WshClient, opts?: RpcOpts): Promise<JobManagerStatusUpdate[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollergetalljobmanagerstatus", null, opts);
        return client.wshRpcCall("jobcontrollergetalljobmanagerstatus", null, opts);
    }

    // command "jobcontrollerlist" [call]
    JobControllerListCommand(client: WshClient, opts?: RpcOpts): Promise<Job[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerlist", null, opts);
        return client.wshRpcCall("jobcontrollerlist", null, opts);
    }

    // command "jobcontrollerreconnectjob" [call]
    JobControllerReconnectJobCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerreconnectjob", data, opts);
        return client.wshRpcCall("jobcontrollerreconnectjob", data, opts);
    }

    // command "jobcontrollerreconnectjobsforconn" [call]
    JobControllerReconnectJobsForConnCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerreconnectjobsforconn", data, opts);
        return client.wshRpcCall("jobcontrollerreconnectjobsforconn", data, opts);
    }

    // command "jobcontrollerstartjob" [call]
    JobControllerStartJobCommand(client: WshClient, data: CommandJobControllerStartJobData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobcontrollerstartjob", data, opts);
        return client.wshRpcCall("jobcontrollerstartjob", data, opts);
    }

    // command "jobinput" [call]
    JobInputCommand(client: WshClient, data: CommandJobInputData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobinput", data, opts);
        return client.wshRpcCall("jobinput", data, opts);
    }

    // command "jobprepareconnect" [call]
    JobPrepareConnectCommand(client: WshClient, data: CommandJobPrepareConnectData, opts?: RpcOpts): Promise<CommandJobConnectRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobprepareconnect", data, opts);
        return client.wshRpcCall("jobprepareconnect", data, opts);
    }

    // command "jobstartstream" [call]
    JobStartStreamCommand(client: WshClient, data: CommandJobStartStreamData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "jobstartstream", data, opts);
        return client.wshRpcCall("jobstartstream", data, opts);
    }

    // command "launchinstalledapp" [call]
    LaunchInstalledAppCommand(client: WshClient, data: CommandLaunchInstalledAppData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "launchinstalledapp", data, opts);
        return client.wshRpcCall("launchinstalledapp", data, opts);
    }

    // command "listinstalledapps" [call]
    ListInstalledAppsCommand(client: WshClient, opts?: RpcOpts): Promise<InstalledAppInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "listinstalledapps", null, opts);
        return client.wshRpcCall("listinstalledapps", null, opts);
    }

    // command "lspquery" [call]
    LspQueryCommand(client: WshClient, data: CommandLspQueryData, opts?: RpcOpts): Promise<CommandLspQueryRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "lspquery", data, opts);
        return client.wshRpcCall("lspquery", data, opts);
    }

    // command "macosversion" [call]
    MacOSVersionCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "macosversion", null, opts);
        return client.wshRpcCall("macosversion", null, opts);
    }

    // command "mcpcalltool" [call]
    McpCallToolCommand(client: WshClient, data: McpCallToolData, opts?: RpcOpts): Promise<McpCallToolResult> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcpcalltool", data, opts);
        return client.wshRpcCall("mcpcalltool", data, opts);
    }

    // command "mcpconnect" [call]
    McpConnectCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcpconnect", data, opts);
        return client.wshRpcCall("mcpconnect", data, opts);
    }

    // command "mcpdisconnect" [call]
    McpDisconnectCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcpdisconnect", data, opts);
        return client.wshRpcCall("mcpdisconnect", data, opts);
    }

    // command "mcpgetstatus" [call]
    McpGetStatusCommand(client: WshClient, opts?: RpcOpts): Promise<{[key: string]: McpStatus}> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcpgetstatus", null, opts);
        return client.wshRpcCall("mcpgetstatus", null, opts);
    }

    // command "mcplistservers" [call]
    McpListServersCommand(client: WshClient, opts?: RpcOpts): Promise<McpServerInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcplistservers", null, opts);
        return client.wshRpcCall("mcplistservers", null, opts);
    }

    // command "mcplisttools" [call]
    McpListToolsCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<McpToolInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "mcplisttools", data, opts);
        return client.wshRpcCall("mcplisttools", data, opts);
    }

    // command "message" [call]
    MessageCommand(client: WshClient, data: CommandMessageData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "message", data, opts);
        return client.wshRpcCall("message", data, opts);
    }

    // command "networkonline" [call]
    NetworkOnlineCommand(client: WshClient, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "networkonline", null, opts);
        return client.wshRpcCall("networkonline", null, opts);
    }

    // command "notify" [call]
    NotifyCommand(client: WshClient, data: WaveNotificationOptions, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "notify", data, opts);
        return client.wshRpcCall("notify", data, opts);
    }

    // command "notifysystemresume" [call]
    NotifySystemResumeCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "notifysystemresume", null, opts);
        return client.wshRpcCall("notifysystemresume", null, opts);
    }

    // command "path" [call]
    PathCommand(client: WshClient, data: PathCommandData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "path", data, opts);
        return client.wshRpcCall("path", data, opts);
    }

    // command "recordtevent" [call]
    RecordTEventCommand(client: WshClient, data: TEvent, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "recordtevent", data, opts);
        return client.wshRpcCall("recordtevent", data, opts);
    }

    // command "remotedisconnectfromjobmanager" [call]
    RemoteDisconnectFromJobManagerCommand(client: WshClient, data: CommandRemoteDisconnectFromJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotedisconnectfromjobmanager", data, opts);
        return client.wshRpcCall("remotedisconnectfromjobmanager", data, opts);
    }

    // command "remotefilecopy" [call]
    RemoteFileCopyCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilecopy", data, opts);
        return client.wshRpcCall("remotefilecopy", data, opts);
    }

    // command "remotefiledelete" [call]
    RemoteFileDeleteCommand(client: WshClient, data: CommandDeleteFileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefiledelete", data, opts);
        return client.wshRpcCall("remotefiledelete", data, opts);
    }

    // command "remotefileinfo" [call]
    RemoteFileInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefileinfo", data, opts);
        return client.wshRpcCall("remotefileinfo", data, opts);
    }

    // command "remotefilejoin" [call]
    RemoteFileJoinCommand(client: WshClient, data: string[], opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilejoin", data, opts);
        return client.wshRpcCall("remotefilejoin", data, opts);
    }

    // command "remotefilemove" [call]
    RemoteFileMoveCommand(client: WshClient, data: CommandFileCopyData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilemove", data, opts);
        return client.wshRpcCall("remotefilemove", data, opts);
    }

    // command "remotefilemultiinfo" [call]
    RemoteFileMultiInfoCommand(client: WshClient, data: CommandRemoteFileMultiInfoData, opts?: RpcOpts): Promise<{[key: string]: FileInfo}> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilemultiinfo", data, opts);
        return client.wshRpcCall("remotefilemultiinfo", data, opts);
    }

    // command "remotefilestream" [call]
    RemoteFileStreamCommand(client: WshClient, data: CommandRemoteFileStreamData, opts?: RpcOpts): Promise<FileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefilestream", data, opts);
        return client.wshRpcCall("remotefilestream", data, opts);
    }

    // command "remotefiletouch" [call]
    RemoteFileTouchCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotefiletouch", data, opts);
        return client.wshRpcCall("remotefiletouch", data, opts);
    }

    // command "remotegetinfo" [call]
    RemoteGetInfoCommand(client: WshClient, opts?: RpcOpts): Promise<RemoteInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotegetinfo", null, opts);
        return client.wshRpcCall("remotegetinfo", null, opts);
    }

    // command "remoteinstallrcfiles" [call]
    RemoteInstallRcFilesCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remoteinstallrcfiles", null, opts);
        return client.wshRpcCall("remoteinstallrcfiles", null, opts);
    }

    // command "remotelistentries" [responsestream]
	RemoteListEntriesCommand(client: WshClient, data: CommandRemoteListEntriesData, opts?: RpcOpts): AsyncGenerator<CommandRemoteListEntriesRtnData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "remotelistentries", data, opts);
        return client.wshRpcStream("remotelistentries", data, opts);
    }

    // command "remotemkdir" [call]
    RemoteMkdirCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotemkdir", data, opts);
        return client.wshRpcCall("remotemkdir", data, opts);
    }

    // command "remotereconnecttojobmanager" [call]
    RemoteReconnectToJobManagerCommand(client: WshClient, data: CommandRemoteReconnectToJobManagerData, opts?: RpcOpts): Promise<CommandRemoteReconnectToJobManagerRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotereconnecttojobmanager", data, opts);
        return client.wshRpcCall("remotereconnecttojobmanager", data, opts);
    }

    // command "remotestartjob" [call]
    RemoteStartJobCommand(client: WshClient, data: CommandRemoteStartJobData, opts?: RpcOpts): Promise<CommandStartJobRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotestartjob", data, opts);
        return client.wshRpcCall("remotestartjob", data, opts);
    }

    // command "remotestreamcpudata" [responsestream]
	RemoteStreamCpuDataCommand(client: WshClient, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "remotestreamcpudata", null, opts);
        return client.wshRpcStream("remotestreamcpudata", null, opts);
    }

    // command "remotestreamfile" [responsestream]
	RemoteStreamFileCommand(client: WshClient, data: CommandRemoteStreamFileData, opts?: RpcOpts): AsyncGenerator<FileData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "remotestreamfile", data, opts);
        return client.wshRpcStream("remotestreamfile", data, opts);
    }

    // command "remoteterminatejobmanager" [call]
    RemoteTerminateJobManagerCommand(client: WshClient, data: CommandRemoteTerminateJobManagerData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remoteterminatejobmanager", data, opts);
        return client.wshRpcCall("remoteterminatejobmanager", data, opts);
    }

    // command "remotewritefile" [call]
    RemoteWriteFileCommand(client: WshClient, data: FileData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "remotewritefile", data, opts);
        return client.wshRpcCall("remotewritefile", data, opts);
    }

    // command "resolveids" [call]
    ResolveIdsCommand(client: WshClient, data: CommandResolveIdsData, opts?: RpcOpts): Promise<CommandResolveIdsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "resolveids", data, opts);
        return client.wshRpcCall("resolveids", data, opts);
    }

    // command "routeannounce" [call]
    RouteAnnounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "routeannounce", null, opts);
        return client.wshRpcCall("routeannounce", null, opts);
    }

    // command "routeunannounce" [call]
    RouteUnannounceCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "routeunannounce", null, opts);
        return client.wshRpcCall("routeunannounce", null, opts);
    }

    // command "sandboxstart" [call]
    SandboxStartCommand(client: WshClient, data: SandboxStartRequest, opts?: RpcOpts): Promise<SandboxStartResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "sandboxstart", data, opts);
        return client.wshRpcCall("sandboxstart", data, opts);
    }

    // command "sandboxstatus" [call]
    SandboxStatusCommand(client: WshClient, data: SandboxStatusRequest, opts?: RpcOpts): Promise<SandboxStatusResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "sandboxstatus", data, opts);
        return client.wshRpcCall("sandboxstatus", data, opts);
    }

    // command "sandboxstop" [call]
    SandboxStopCommand(client: WshClient, data: SandboxStopRequest, opts?: RpcOpts): Promise<SandboxStopResponse> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "sandboxstop", data, opts);
        return client.wshRpcCall("sandboxstop", data, opts);
    }

    // command "sendtelemetry" [call]
    SendTelemetryCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "sendtelemetry", null, opts);
        return client.wshRpcCall("sendtelemetry", null, opts);
    }

    // command "setblockfocus" [call]
    SetBlockFocusCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setblockfocus", data, opts);
        return client.wshRpcCall("setblockfocus", data, opts);
    }

    // command "setconfig" [call]
    SetConfigCommand(client: WshClient, data: SettingsType, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setconfig", data, opts);
        return client.wshRpcCall("setconfig", data, opts);
    }

    // command "setconnectionsconfig" [call]
    SetConnectionsConfigCommand(client: WshClient, data: ConnConfigRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setconnectionsconfig", data, opts);
        return client.wshRpcCall("setconnectionsconfig", data, opts);
    }

    // command "setmeta" [call]
    SetMetaCommand(client: WshClient, data: CommandSetMetaData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setmeta", data, opts);
        return client.wshRpcCall("setmeta", data, opts);
    }

    // command "setpeerinfo" [call]
    SetPeerInfoCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setpeerinfo", data, opts);
        return client.wshRpcCall("setpeerinfo", data, opts);
    }

    // command "setrtinfo" [call]
    SetRTInfoCommand(client: WshClient, data: CommandSetRTInfoData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setrtinfo", data, opts);
        return client.wshRpcCall("setrtinfo", data, opts);
    }

    // command "setsecrets" [call]
    SetSecretsCommand(client: WshClient, data: {[key: string]: string}, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setsecrets", data, opts);
        return client.wshRpcCall("setsecrets", data, opts);
    }

    // command "setvar" [call]
    SetVarCommand(client: WshClient, data: CommandVarData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "setvar", data, opts);
        return client.wshRpcCall("setvar", data, opts);
    }

    // command "startjob" [call]
    StartJobCommand(client: WshClient, data: CommandStartJobData, opts?: RpcOpts): Promise<CommandStartJobRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "startjob", data, opts);
        return client.wshRpcCall("startjob", data, opts);
    }

    // command "streamcpudata" [responsestream]
	StreamCpuDataCommand(client: WshClient, data: CpuDataRequest, opts?: RpcOpts): AsyncGenerator<TimeSeriesData, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "streamcpudata", data, opts);
        return client.wshRpcStream("streamcpudata", data, opts);
    }

    // command "streamdata" [call]
    StreamDataCommand(client: WshClient, data: CommandStreamData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "streamdata", data, opts);
        return client.wshRpcCall("streamdata", data, opts);
    }

    // command "streamdataack" [call]
    StreamDataAckCommand(client: WshClient, data: CommandStreamAckData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "streamdataack", data, opts);
        return client.wshRpcCall("streamdataack", data, opts);
    }

    // command "streamtest" [responsestream]
	StreamTestCommand(client: WshClient, opts?: RpcOpts): AsyncGenerator<number, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "streamtest", null, opts);
        return client.wshRpcStream("streamtest", null, opts);
    }

    // command "streamwaveai" [responsestream]
	StreamWaveAiCommand(client: WshClient, data: WaveAIStreamRequest, opts?: RpcOpts): AsyncGenerator<WaveAIPacketType, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "streamwaveai", data, opts);
        return client.wshRpcStream("streamwaveai", data, opts);
    }

    // command "tabgrouplist" [call]
    TabGroupListCommand(client: WshClient, opts?: RpcOpts): Promise<TabGroupInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "tabgrouplist", null, opts);
        return client.wshRpcCall("tabgrouplist", null, opts);
    }

    // command "termgetscrollbacklines" [call]
    TermGetScrollbackLinesCommand(client: WshClient, data: CommandTermGetScrollbackLinesData, opts?: RpcOpts): Promise<CommandTermGetScrollbackLinesRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "termgetscrollbacklines", data, opts);
        return client.wshRpcCall("termgetscrollbacklines", data, opts);
    }

    // command "test" [call]
    TestCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "test", data, opts);
        return client.wshRpcCall("test", data, opts);
    }

    // command "testmultiarg" [call]
    TestMultiArgCommand(client: WshClient, arg1: string, arg2: number, arg3: boolean, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "testmultiarg", { args: [arg1, arg2, arg3] }, opts);
        return client.wshRpcCall("testmultiarg", { args: [arg1, arg2, arg3] }, opts);
    }

    // command "ungrouptabs" [call]
    UngroupTabsCommand(client: WshClient, data: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "ungrouptabs", data, opts);
        return client.wshRpcCall("ungrouptabs", data, opts);
    }

    // command "updatetabgroup" [call]
    UpdateTabGroupCommand(client: WshClient, data: UpdateTabGroupData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "updatetabgroup", data, opts);
        return client.wshRpcCall("updatetabgroup", data, opts);
    }

    // command "updatetabname" [call]
    UpdateTabNameCommand(client: WshClient, arg1: string, arg2: string, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "updatetabname", { args: [arg1, arg2] }, opts);
        return client.wshRpcCall("updatetabname", { args: [arg1, arg2] }, opts);
    }

    // command "updateworkspacetabids" [call]
    UpdateWorkspaceTabIdsCommand(client: WshClient, arg1: string, arg2: string[], opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "updateworkspacetabids", { args: [arg1, arg2] }, opts);
        return client.wshRpcCall("updateworkspacetabids", { args: [arg1, arg2] }, opts);
    }

    // command "vdomasyncinitiation" [call]
    VDomAsyncInitiationCommand(client: WshClient, data: VDomAsyncInitiationRequest, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vdomasyncinitiation", data, opts);
        return client.wshRpcCall("vdomasyncinitiation", data, opts);
    }

    // command "vdomcreatecontext" [call]
    VDomCreateContextCommand(client: WshClient, data: VDomCreateContext, opts?: RpcOpts): Promise<ORef> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "vdomcreatecontext", data, opts);
        return client.wshRpcCall("vdomcreatecontext", data, opts);
    }

    // command "vdomrender" [responsestream]
	VDomRenderCommand(client: WshClient, data: VDomFrontendUpdate, opts?: RpcOpts): AsyncGenerator<VDomBackendUpdate, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "vdomrender", data, opts);
        return client.wshRpcStream("vdomrender", data, opts);
    }

    // command "vdomurlrequest" [responsestream]
	VDomUrlRequestCommand(client: WshClient, data: VDomUrlRequestData, opts?: RpcOpts): AsyncGenerator<VDomUrlRequestResponse, void, boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcStream(client, "vdomurlrequest", data, opts);
        return client.wshRpcStream("vdomurlrequest", data, opts);
    }

    // command "waitforroute" [call]
    WaitForRouteCommand(client: WshClient, data: CommandWaitForRouteData, opts?: RpcOpts): Promise<boolean> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waitforroute", data, opts);
        return client.wshRpcCall("waitforroute", data, opts);
    }

    // command "waveaiaddcontext" [call]
    WaveAIAddContextCommand(client: WshClient, data: CommandWaveAIAddContextData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveaiaddcontext", data, opts);
        return client.wshRpcCall("waveaiaddcontext", data, opts);
    }

    // command "waveaienabletelemetry" [call]
    WaveAIEnableTelemetryCommand(client: WshClient, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveaienabletelemetry", null, opts);
        return client.wshRpcCall("waveaienabletelemetry", null, opts);
    }

    // command "waveaigettooldiff" [call]
    WaveAIGetToolDiffCommand(client: WshClient, data: CommandWaveAIGetToolDiffData, opts?: RpcOpts): Promise<CommandWaveAIGetToolDiffRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveaigettooldiff", data, opts);
        return client.wshRpcCall("waveaigettooldiff", data, opts);
    }

    // command "waveaitoolapprove" [call]
    WaveAIToolApproveCommand(client: WshClient, data: CommandWaveAIToolApproveData, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveaitoolapprove", data, opts);
        return client.wshRpcCall("waveaitoolapprove", data, opts);
    }

    // command "wavefilereadstream" [call]
    WaveFileReadStreamCommand(client: WshClient, data: CommandWaveFileReadStreamData, opts?: RpcOpts): Promise<WaveFileInfo> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "wavefilereadstream", data, opts);
        return client.wshRpcCall("wavefilereadstream", data, opts);
    }

    // command "waveinfo" [call]
    WaveInfoCommand(client: WshClient, opts?: RpcOpts): Promise<WaveInfoData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "waveinfo", null, opts);
        return client.wshRpcCall("waveinfo", null, opts);
    }

    // command "webeval" [call]
    WebEvalCommand(client: WshClient, data: CommandWebEvalData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "webeval", data, opts);
        return client.wshRpcCall("webeval", data, opts);
    }

    // command "webselector" [call]
    WebSelectorCommand(client: WshClient, data: CommandWebSelectorData, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "webselector", data, opts);
        return client.wshRpcCall("webselector", data, opts);
    }

    // command "widgetclear" [call]
    WidgetClearCommand(client: WshClient, data: CommandWidgetClearData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetclear", data, opts);
        return client.wshRpcCall("widgetclear", data, opts);
    }

    // command "widgetclick" [call]
    WidgetClickCommand(client: WshClient, data: CommandWidgetClickData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetclick", data, opts);
        return client.wshRpcCall("widgetclick", data, opts);
    }

    // command "widgetclipboardget" [call]
    WidgetClipboardGetCommand(client: WshClient, data: CommandWidgetClipboardGetData, opts?: RpcOpts): Promise<WidgetClipboardGetRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetclipboardget", data, opts);
        return client.wshRpcCall("widgetclipboardget", data, opts);
    }

    // command "widgetclipboardset" [call]
    WidgetClipboardSetCommand(client: WshClient, data: CommandWidgetClipboardSetData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetclipboardset", data, opts);
        return client.wshRpcCall("widgetclipboardset", data, opts);
    }

    // command "widgetdrag" [call]
    WidgetDragCommand(client: WshClient, data: CommandWidgetDragData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetdrag", data, opts);
        return client.wshRpcCall("widgetdrag", data, opts);
    }

    // command "widgetelementat" [call]
    WidgetElementAtCommand(client: WshClient, data: CommandWidgetElementAtData, opts?: RpcOpts): Promise<WidgetElementAtRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetelementat", data, opts);
        return client.wshRpcCall("widgetelementat", data, opts);
    }

    // command "widgetfind" [call]
    WidgetFindCommand(client: WshClient, data: CommandWidgetFindData, opts?: RpcOpts): Promise<WidgetFindRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetfind", data, opts);
        return client.wshRpcCall("widgetfind", data, opts);
    }

    // command "widgetgetelements" [call]
    WidgetGetElementsCommand(client: WshClient, data: CommandWidgetGetElementsData, opts?: RpcOpts): Promise<WidgetGetElementsRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetgetelements", data, opts);
        return client.wshRpcCall("widgetgetelements", data, opts);
    }

    // command "widgetgetstate" [call]
    WidgetGetStateCommand(client: WshClient, data: CommandWidgetGetStateData, opts?: RpcOpts): Promise<WidgetGetStateRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetgetstate", data, opts);
        return client.wshRpcCall("widgetgetstate", data, opts);
    }

    // command "widgetgetvalue" [call]
    WidgetGetValueCommand(client: WshClient, data: CommandWidgetGetValueData, opts?: RpcOpts): Promise<WidgetGetValueRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetgetvalue", data, opts);
        return client.wshRpcCall("widgetgetvalue", data, opts);
    }

    // command "widgethover" [call]
    WidgetHoverCommand(client: WshClient, data: CommandWidgetHoverData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgethover", data, opts);
        return client.wshRpcCall("widgethover", data, opts);
    }

    // command "widgetinspect" [call]
    WidgetInspectCommand(client: WshClient, data: CommandWidgetInspectData, opts?: RpcOpts): Promise<WidgetInspectRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetinspect", data, opts);
        return client.wshRpcCall("widgetinspect", data, opts);
    }

    // command "widgetkeyboardpress" [call]
    WidgetKeyboardPressCommand(client: WshClient, data: CommandWidgetKeyboardPressData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetkeyboardpress", data, opts);
        return client.wshRpcCall("widgetkeyboardpress", data, opts);
    }

    // command "widgetkeyboardtype" [call]
    WidgetKeyboardTypeCommand(client: WshClient, data: CommandWidgetKeyboardTypeData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetkeyboardtype", data, opts);
        return client.wshRpcCall("widgetkeyboardtype", data, opts);
    }

    // command "widgetlongpress" [call]
    WidgetLongPressCommand(client: WshClient, data: CommandWidgetLongPressData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetlongpress", data, opts);
        return client.wshRpcCall("widgetlongpress", data, opts);
    }

    // command "widgetmouseclick" [call]
    WidgetMouseClickCommand(client: WshClient, data: CommandWidgetMouseClickData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetmouseclick", data, opts);
        return client.wshRpcCall("widgetmouseclick", data, opts);
    }

    // command "widgetmousedrag" [call]
    WidgetMouseDragCommand(client: WshClient, data: CommandWidgetMouseDragData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetmousedrag", data, opts);
        return client.wshRpcCall("widgetmousedrag", data, opts);
    }

    // command "widgetmousescroll" [call]
    WidgetMouseScrollCommand(client: WshClient, data: CommandWidgetMouseScrollData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetmousescroll", data, opts);
        return client.wshRpcCall("widgetmousescroll", data, opts);
    }

    // command "widgetscreenshotannotated" [call]
    WidgetScreenshotAnnotatedCommand(client: WshClient, data: CommandWidgetScreenshotAnnotatedData, opts?: RpcOpts): Promise<WidgetScreenshotAnnotatedRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetscreenshotannotated", data, opts);
        return client.wshRpcCall("widgetscreenshotannotated", data, opts);
    }

    // command "widgetscrollto" [call]
    WidgetScrollToCommand(client: WshClient, data: CommandWidgetScrollToData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetscrollto", data, opts);
        return client.wshRpcCall("widgetscrollto", data, opts);
    }

    // command "widgetselect" [call]
    WidgetSelectCommand(client: WshClient, data: CommandWidgetSelectData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetselect", data, opts);
        return client.wshRpcCall("widgetselect", data, opts);
    }

    // command "widgetsetvalue" [call]
    WidgetSetValueCommand(client: WshClient, data: CommandWidgetSetValueData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetsetvalue", data, opts);
        return client.wshRpcCall("widgetsetvalue", data, opts);
    }

    // command "widgetsnapshot" [call]
    WidgetSnapshotCommand(client: WshClient, data: CommandWidgetSnapshotData, opts?: RpcOpts): Promise<WidgetSnapshotRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetsnapshot", data, opts);
        return client.wshRpcCall("widgetsnapshot", data, opts);
    }

    // command "widgettoggle" [call]
    WidgetToggleCommand(client: WshClient, data: CommandWidgetToggleData, opts?: RpcOpts): Promise<WidgetMouseActionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgettoggle", data, opts);
        return client.wshRpcCall("widgettoggle", data, opts);
    }

    // command "widgetwaitcondition" [call]
    WidgetWaitConditionCommand(client: WshClient, data: CommandWidgetWaitConditionData, opts?: RpcOpts): Promise<WidgetWaitConditionRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetwaitcondition", data, opts);
        return client.wshRpcCall("widgetwaitcondition", data, opts);
    }

    // command "widgetwaitforelement" [call]
    WidgetWaitForElementCommand(client: WshClient, data: CommandWidgetWaitForElementData, opts?: RpcOpts): Promise<WidgetWaitForElementRtnData> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "widgetwaitforelement", data, opts);
        return client.wshRpcCall("widgetwaitforelement", data, opts);
    }

    // command "windowlist" [call]
    WindowListCommand(client: WshClient, opts?: RpcOpts): Promise<WindowInfo[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "windowlist", null, opts);
        return client.wshRpcCall("windowlist", null, opts);
    }

    // command "workspacelist" [call]
    WorkspaceListCommand(client: WshClient, opts?: RpcOpts): Promise<WorkspaceInfoData[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "workspacelist", null, opts);
        return client.wshRpcCall("workspacelist", null, opts);
    }

    // command "workspacesurfacecontrol" [call]
    WorkspaceSurfaceControlCommand(client: WshClient, data: CommandWorkspaceSurfaceControlData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "workspacesurfacecontrol", data, opts);
        return client.wshRpcCall("workspacesurfacecontrol", data, opts);
    }

    // command "workspacesurfacescreenshot" [call]
    WorkspaceSurfaceScreenshotCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "workspacesurfacescreenshot", null, opts);
        return client.wshRpcCall("workspacesurfacescreenshot", null, opts);
    }

    // command "workspacesurfacesnapshot" [call]
    WorkspaceSurfaceSnapshotCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "workspacesurfacesnapshot", null, opts);
        return client.wshRpcCall("workspacesurfacesnapshot", null, opts);
    }

    // command "writetempfile" [call]
    WriteTempFileCommand(client: WshClient, data: CommandWriteTempFileData, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "writetempfile", data, opts);
        return client.wshRpcCall("writetempfile", data, opts);
    }

    // command "wshactivity" [call]
    WshActivityCommand(client: WshClient, data: {[key: string]: number}, opts?: RpcOpts): Promise<void> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "wshactivity", data, opts);
        return client.wshRpcCall("wshactivity", data, opts);
    }

    // command "wsldefaultdistro" [call]
    WslDefaultDistroCommand(client: WshClient, opts?: RpcOpts): Promise<string> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "wsldefaultdistro", null, opts);
        return client.wshRpcCall("wsldefaultdistro", null, opts);
    }

    // command "wsllist" [call]
    WslListCommand(client: WshClient, opts?: RpcOpts): Promise<string[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "wsllist", null, opts);
        return client.wshRpcCall("wsllist", null, opts);
    }

    // command "wslstatus" [call]
    WslStatusCommand(client: WshClient, opts?: RpcOpts): Promise<ConnStatus[]> {
        if (this.mockClient) return this.mockClient.mockWshRpcCall(client, "wslstatus", null, opts);
        return client.wshRpcCall("wslstatus", null, opts);
    }

}

export const RpcApi = new RpcApiType();
